compressionLevel: mixed
enableGlobalCache: false
nodeLinker: node-modules
npmScopes: {
  arthurhovhannisyan31: {
    npmPublishRegistry: "https://npm.pkg.github.com",
    npmRegistryServer: "https://npm.pkg.github.com",
    npmAuthToken: "${NODE_AUTH_TOKEN-}",
    npmAlwaysAuth: true
  }
}
