#!/bin/bash

. "$(dirname "$0")/configs/colors"

validate () {
  for COMMAND in $1;
  do
   printf "⏳ Running: $COMMAND \n"
   if ! yarn $COMMAND
   then
       printf "⛔ ${RED} Failed to check: $COMMAND \n${NC}"
       exit 1
   fi
   printf "✅ ${GREEN} Success: $COMMAND \n\n${NC}"
  done
}
