name: Publish package
inputs:
  node-auth-token:
    description: Auth token
    required: true
  registry-url:
    description: Target registry URL
    required: true
runs:
  using: "composite"
  steps:
    - name: Install NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        registry-url: ${{ inputs.registry-url }}
    - name: Enable yarn
      shell: bash
      run: corepack enable
    - name: Restore dependencies
      id: restore-dependencies
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install Packages
      shell: bash
      if: ${{ steps.restore-dependencies.outputs.cache-hit != 'true' }}
      run: yarn
    - name: Build distribution
      shell: bash
      run: yarn build
    - name: Publish
      shell: bash
      env:
        NODE_AUTH_TOKEN: ${{ inputs.node-auth-token }}
      run: yarn npm publish --provenance --access public
