name: Publish
description: Publish package to registry
inputs:
  node-auth-token:
    description: Auth token
    required: true
  registry-url:
    description: Target registry URL
    required: true
runs:
  using: "composite"
  steps:
    - name: Install NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        registry-url: ${{ inputs.registry-url }}
    - name: Enable yarn
      shell: bash
      run: corepack enable
    - name: Log
      shell: bash
      run: |
        ls -al .
#    - name: Publish
#      shell: bash
#      env:
#        NODE_AUTH_TOKEN: ${{ inputs.node-auth-token }}
#      run: yarn npm publish --provenance --access public
