name: Validate Code
on:
  push:
    branches:
      - '*'
env:
  HUSKY: 0
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  validate-code:
    name: JS validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
      - name: Enable yarn
        shell: bash
        run: corepack enable
      - name: Restore dependencies
        id: restore-dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Packages
        if: ${{ steps.restore-dependencies.outputs.cache-hit != 'true' }}
        run: yarn
      - name: Validate types
        run: yarn types
      - name: Validate linters
        run: yarn lint
